# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lizz < Formula
  desc ""
  homepage "https://github.com/openlizz/lizz"
  version "0.0.1-alpha.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1-alpha.1/lizz_0.0.1-alpha.1_darwin_amd64.tar.gz"
      sha256 "e15b74b214f3dc70b37f6f1d855a7803ef1ce604327f72a45ce9f19414695896"

      def install
        bin.install "lizz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1-alpha.1/lizz_0.0.1-alpha.1_darwin_arm64.tar.gz"
      sha256 "aa0feeb24e8d933ee2bd6194a86cd82d45087d522d112d069d3b096c7a86fdb6"

      def install
        bin.install "lizz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1-alpha.1/lizz_0.0.1-alpha.1_linux_arm64.tar.gz"
      sha256 "158ec2c6079d61a1dc3d142825431dd59d13ce693c8e188279b68ff50b4f3104"

      def install
        bin.install "lizz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1-alpha.1/lizz_0.0.1-alpha.1_linux_amd64.tar.gz"
      sha256 "18d50baec3fbc08e4e4bf78bd6279d65bc615bdf37d47d617c28f48ae790fcba"

      def install
        bin.install "lizz"
      end
    end
  end
end
