# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lizz < Formula
  desc "CLI to facilitate the management of a Flux2 k8s cluster"
  homepage "https://github.com/openlizz/lizz"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1/lizz_0.0.1_darwin_amd64.tar.gz"
      sha256 "1b4adbb9d5ce58e2d5034c157892d1cb0ef0f730de713625c49da003bb8034ba"

      def install
        bin.install "lizz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1/lizz_0.0.1_darwin_arm64.tar.gz"
      sha256 "7050dd667aed3086199052fa771a3082ccf757b3e5fa9b37e71607307d32a45d"

      def install
        bin.install "lizz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1/lizz_0.0.1_linux_arm64.tar.gz"
      sha256 "0f4c88dd6c6e32365a10b22a2ae965b51910de6c344fc0d42f24e665b671645f"

      def install
        bin.install "lizz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Openlizz/lizz/releases/download/v0.0.1/lizz_0.0.1_linux_amd64.tar.gz"
      sha256 "4f32f0e01b3991aa80415bbf3132fff651292911dd432afc6d416f4ba2a19ac2"

      def install
        bin.install "lizz"
      end
    end
  end
end
